### PR TITLE
fix #1847: bug connected with stranger job names was fixed

### LINKED ISSUE #1847: Testrun names are incorrect
image

It changes spaces with %20

### PR DESCRIPTION
**Pull request by Boniara**
fixes #1847

### CODE REVIEW

File: sources/zafira-services/src/main/java/com/qaprosoft/zafira/service/JobsService.java [hunk 1]
```diff
@@ -62,11 +70,21 @@ private Job createJobFromURL(String jobUrl, Long userId) {
         // Replacing trailing slash we make sure that further operations
         // based on splitting by slash will be performed correctly
         jobUrl = jobUrl.replaceAll("/$", "");
-        String jobName = StringUtils.substringAfterLast(jobUrl, "/");
+        String jobName = retrieveJobName(jobUrl);
         String jenkinsHost = parseJenkinsHost(jobUrl);
         return new Job(jobName, jobUrl, jenkinsHost, user);
     }
```
Comment (nsidorevich) [inline sources/zafira-services/src/main/java/com/qaprosoft/zafira/service/JobsService.java]: reformat like this please:
```java
    public static String retrieveJobName(String jobUrl) {
        try {
            String decodedJobUrl = URLDecoder.decode(jobUrl, StandardCharsets.UTF_8.toString());
            return StringUtils.substringAfterLast(decodedJobUrl, "/");
        } catch (UnsupportedEncodingException e) {
            throw new ProcessingException(UNPROCESSABLE_URL, String.format(ERR_MSG_UNABLE_TO_PARSE_URI, jobUrl));
        }
    }
```
